gcc:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=g++ check
  artifacts:
    paths:
      - "libdlh.a"

gcc-legacy:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=g++ LEGACY=1 check
  artifacts:
    paths:
      - "libdlh.a"

clang:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=clang++ check
  artifacts:
    paths:
      - "libdlh.a"

clang-legacy:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=clang++ LEGACY=1 check
  artifacts:
    paths:
      - "libdlh.a"

style:
  image: inf4/luci:ubuntu-jammy
  script:
    - make lint
    - make tidy
